version: '3'

services:
  odoo:
    container_name: odoo-odoo
    image: odoo:15
    restart: always
    ports:
      - 8069:8069
    depends_on:
      - db
    volumes:
      - ./odoo/config/:/etc/odoo
      - ./odoo/addons/:/mnt/extra-addons
      - ./odoo/logs/:/var/log/odoo


  db:
    container_name: postgres-odoo
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /data/${PROJECT_NAME}:/var/lib/postgresql/data/pgdata

volumes:
  db: {}
